# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 0.1.$(Rev:r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    arguments: '--no-build --logger trx --configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Package NuGet into artifacts
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj;!**/*.Test.csproj'
    nobuild: true
    versioningScheme: 'byBuildNumber'
    verbosityPack: 'Normal'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'